export const LOAD_GROCERY = 'LOAD_GROCERY';
export const ADD_GROCERY = 'ADD_GROCERY';
export const ACQUIRE_GROCERY = 'ACQUIRE_GROCERY';
export const CANCEL_ACQUIRE_GROCERY = 'CANCEL_ACQUIRE_GROCERY';
export const DELETE_GROCERY = 'DELETE_GROCERY';